### PR TITLE
spring(clean) - remove questionable CSS

### PR DESCRIPTION
**Pull request by maltenuhn**
**Problem:**
Eni was trying to use a `button` that had non-pedigree styling of questionable lineage. It was ultimately traced back to one of a series of a ~legacy~ ~memorabilia~ ~flashback-inducing~ css files. 

**Fix:**
No css, no problem.

**Commit Details:**
- Remove contents from `control-slider.css` and its siblings
- Quick optical check to verify nothing broke badly
- Shed a tear for the expression editor

### CODE REVIEW

**Review by enidemi — APPROVED** [review]

**Review by Rheeseyb — APPROVED** [review]
Probably fine :grin:

**Comment by Rheeseyb** [comment]
Actually... something must be importing these

**Comment by Rheeseyb** [comment]
@maltenuhn this array needs updating: https://github.com/concrete-utopia/utopia/blob/master/editor/src/templates/editor-entry-point.tsx#L18

**Comment by maltenuhn** [comment]
> Actually... something must be importing these

@Rheeseyb I'll remove the actual the files in a separate PR, just on the offchance it _does_ affect anything not top of mind that we'll spot

**Pull request merged**
