### PR TITLE
Introduce caching around TemplatePath creation

### PR DESCRIPTION
**Pull request by Rheeseyb**
**Problem:**
We are repeatedly creating new `TemplatePath` s over and over in our editor.

**Fix:**
I have copied the style set out by [`property-path.ts`](https://github.com/concrete-utopia/utopia/blob/master/editor/src/core/shared/property-path.ts) for caching, but adjusted it to support the more complex nature of `TemplatePath` s.

### CODE REVIEW

**Comment by seanparsons** [comment]
Doesn't this run the risk of the cache expanding infinitely?

**Comment by balazsbajorics** [comment]
> Doesn't this run the risk of the cache expanding infinitely?

+1 to this.

when the code file is re-parsed, every uid is regenerated. 
1. that means that if you edit the code file a lot, we'll end up with a ton of unused template paths
2. it also means that the code file parsing is a good point to flush this cache

**Comment by Rheeseyb** [comment]
> Doesn't this run the risk of the cache expanding infinitely?

Hmmm good point. We have the same issue with the property path cache too. Seems both should be cleared whenever we trigger a parse of the code. I'll see how dangerous that is...

**Comment by Rheeseyb** [comment]
@balazsbajorics @seanparsons OK I have updated the flow to trigger a cache clear (for both the `TemplatePath` and `PropertyPath`) after each parse (as part of the handling of the `UPDATE_FROM_WORKER` action).

**Review by seanparsons — APPROVED** [review]

**Review by balazsbajorics — APPROVED** [review]

**Pull request merged**
