### PR TITLE
fix(left-pane) Fix settings related typo

### PR DESCRIPTION
**Pull request by charkour**
**Problem:**
Incorrect description and typo in left-pane settings tab.

**Fix:**
Fixes the description and the typo.

### CODE REVIEW

**Comment by maltenuhn** [comment]
Nice - thanks for the PR :)

**Review by Rheeseyb — APPROVED** [review]
Good catch, thanks!

**Comment by ck-tekton** [comment]
Cheers!

**Comment by charkour** [comment]
Cheers!

**Pull request merged**
