### PR TITLE
action added to deselect control

### PR DESCRIPTION
**Pull request by OmarDaSilva**
Navigator Component Fix and Feature added 

Problem:
When deselecting a component on the canvas, the deselected component is still shown selected on the navigator component
Fix:
Added action EditorActions.setFocusedElement(null) to deselect control
Added offset scroll when an element is "set as focused element" #

### CODE REVIEW

**Review by enidemi — APPROVED** [review]

**Comment by OmarDaSilva** [comment]
This PR is now ready for feedback please

**Review by seanparsons — APPROVED** [review]

**Comment by enidemi** [comment]
Extended this PR with the following features:
- scroll animation is enabled when a component is focused from the contextmenu
- changed the scroll position to always be at 20,60 as the default project

**Review by balazsbajorics — APPROVED** [review]

**Comment by maltenuhn** [comment]
I'm gonna merge this since it _really_ helps with testing

**Comment by maltenuhn** [comment]
Ok, so after testing this _after_ merging - this doesn't seem to do anything! 

I tried to figure out why, and it seems like the `DeselectControl` is no longer even doing _any_ deselecting. In fact, when I comment out the event handler there, the editor still deselects. Elsewhere, `select-mode-control-container` has a `clearSelection()` function that... doesn't seem to be called by anything.

And yet: I click on the empty canvas and the editor deselects.

 @balazsbajorics do you know where the deselection logic _actually_ lives nowadays?

**Pull request merged**
